### ISSUE TITLE
[FEATURE] Support for Firefox browser engine.

### ISSUE THREAD

**Issue by tanmaysharma2001** [EmergenceAI/Agent-E#111]
### Title
Support for Firefox Browser Engine in Agent-e

### Description
Request to add support for firefox browser engine in agent-e.

### Problem Background
Currently, Agent-e is limited to the Chromium engine, which may not always be compatible with specific websites or applications optimized for Firefox. Adding Firefox support would allow users to leverage Firefox-specific features, improve compatibility, and enhance privacy controls, especially for web applications that perform better on Firefox or require unique Firefox configurations. This flexibility is crucial for users in environments where Firefox is the preferred or mandated browser.

### Proposed Solution
Integrate the Firefox browser engine as an alternative to the Chromium engine within Agent-e, allowing users to switch between the two based on their needs. This could be implemented as an option in the settings, where users can select the preferred browser engine.

**Comment by deepak-akkil** [comment]
Hey Tanmay, 
It is indeed true that today today "chrome" is hardcoded in the playwright manager. 
https://github.com/EmergenceAI/Agent-E/blob/master/ae/core/playwright_manager.py#L152

Playwright supports other browser instances such as msedge and firefox, https://playwright.dev/docs/browsers.
So supporting this will in practice needs some updates to playwright manager. 

Is this something you can try out and put a PR against? Otherwise, this is in our to-do list and will hopefully get there soon.

**Comment by tanmaysharma2001** [comment]
@deepak-akkil I tried integrating firefox like this:
```python
elif self.browser_type == "firefox":
            logger.info(f"User dir: {user_dir}")
            try:
                PlaywrightManager._browser_context = await PlaywrightManager._playwright.firefox.launch_persistent_context(user_dir,
                    headless=self.isheadless,
                    args=["--disable-blink-features=AutomationControlled",
                          "--disable-session-crashed-bubble",  # disable the restore session bubble
                          "--disable-infobars",  # disable informational popups,
                          ],
                    no_viewport=True
                )
            except Exception as e:
                if "Target page, context or browser has been closed" in str(e):
                    new_user_dir = tempfile.mkdtemp()
                    logger.error(f"Failed to launch persistent context with user dir {user_dir}: {e} Trying to launch with a new user dir {new_user_dir}")
                    PlaywrightManager._browser_context = await PlaywrightManager._playwright.firefox.launch_persistent_context(new_user_dir,
                        headless=self.isheadless,
                        args=["--disable-blink-features=AutomationControlled",
                              "--disable-session-crashed-bubble",  # disable the restore session bubble
                              "--disable-infobars",  # disable informational popups,
                              ],
                        no_viewport=True
                    )
                else:
                    raise e from None
```

and it was able to spin up a firefox engine. The only issue this created the mutation observer in dom changes failing to detect any changes. Any idea how that can be fixed?

**Comment by deepak-akkil** [comment]
Great. Could you push this as a draft PR. I can then troubleshoot why MutationObserver is not working as expected locally. 

At a high level, how mutation observation works today is:
a) We inject a mutation observer (js) to the page on page navigation. You can verify that this is working as expected by checking if you see a console log in the browser along the lines of "Mutation Observer loaded".
b) Then during every skill execution, the skills listens to this stream. We also do have some basic filtering in the mutation observer so that we do not add irrelevant stuff to the LLM context. If something is going wrong here on firefox, you need to add some logs to the dom_mutation_observor.py to see what maybe going on. 

I can also take a look if i can access your branch somehow.

**Comment by tanmaysharma2001** [comment]
will do, thanks!

**Comment by teaxio** [comment]
Closing this for now since the outcome will be a PR. Please reopen @tanmaysharma2001 if there's more to discuss here.
